title: Interoperability
hide: false
nav:
  - 'Create Connected Contracts with Cross-Chain Protocols':
    - protocols.index.md
    - '[Axelar] Minting a Cross-Chain NFT': 'using-axelar-sdk.md'
  - 'Build Cross-Chain Applications with XCM':
    - xcm.index.md
    - "[Polkadot's XCM Pallet] Remote Staking on Moonbeam from Polkadot": 'remote-staking-xcm.md'
    - "[Polkadot's XCM Pallet] Uniswap V2 Swap on Moonbeam from Polkadot": 'uniswapv2-swap-xcm.md'
    - "[Polkadot's XCM Pallet] Batched Remote EVM Calls on Moonbeam from Polkadot": 'remote-batched-evm-calls.md'
