title: Core Concepts
nav:
  - index.md
  - 'Account Balances': 'balances.md'
  - 'Balance Transfers': 'transfers-api.md'
  - 'Consensus & Finality': 'consensus-finality.md'
  - 'Transaction Fees': 'tx-fees.md'
  - 'Unified Accounts': 'unified-accounts.md'
  - 'Security Considerations': 'security.md'
  - 'Glossary': 'glossary.md'
