title: Features
nav:
  - index.md
  - 'Cross-Chain Communication': 'xchain-plans.md'
  - 'Ethereum Compatibility': 'eth-compatibility.md'
  - 'Governance': 'governance.md'
  - 'Parachain Consensus': 'consensus.md'
  - 'Randomness': 'randomness.md'
  - 'Staking': 'staking.md'
  - 'Treasury': 'treasury.md'
