title: Features
nav:
  - index.md
  - 'Ethereum Compatibility': 'eth-compatibility.md'
  - 'Governance': 'governance.md'
  - 'Randomness': 'randomness.md'
  - 'Staking': 'staking.md'
  - 'Treasury': 'treasury.md'
  - 'Glossary': 'glossary.md'
