title: Collators
nav:
  - index.md
  - 'Overview': 'overview.md'
  - 'FAQ': 'faq.md'
  - 'Requirements': 'requirements.md'
  - 'Account Management': 'account-management.md'
  - 'Author Mapping Precompile': 'author-mapping.md'
  - 'Collator Activities': 'activities.md'
  - 'Orbiter Program': 'orbiter.md'
