title: Platform
nav:
  - index.md
  - networks
  - 'Vision': 'vision.md'
  - 'Why Polkadot': 'why-polkadot.md'
  - 'Technology & Architecture': 'technology.md'
  - 'Tokens': 'tokens.md'
  - 'Glossary': 'glossary.md'
